version: '3.8'

services:
  coupon-api:
    container_name: coupon-api
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - h2-data:/data   # mantém dados do H2 persistentes

volumes:
  h2-data: